config/routes.rb
Rails.application.routes.draw do

resources :users do 
  resources :posts, except: [:edit, :update, :destroy] do
    resources :comments, only: :create
  end
end

  root 'users#new'

  
  get '/signup' => 'users#new'
  resources :friends

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :body, type: String

embedded_in :post

	def date_added
	  created_at.localtime.strftime("%-m/%-d/%Y | %l:%M %p")
	end

end

app/models/friend.rb
class Friend
  include Mongoid::Document
  field :firstname, type: String
  field :lastname, type: String
  field :email, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: String
  field :password, type: String

  def fullname
	self.firstname + " " + self.lastname
  end

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :body, type: String
  

belongs_to :user
embeds_many :comments

def date_published
  created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
end

end

app/models/user.rb
class User
  include Mongoid::Document
  field :firstname, type: String
  field :lastname, type: String
  field :email, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: String
  field :password, type: String
  field :friends, default: [], type: Array
  field :password_digest, type: String
  mount_uploader :image, AvatarUploader
  attr_reader :password

  has_many :posts

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end

  validates :firstname, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }, on: :create

  def fullname
  	self.firstname + " " + self.lastname
  end

  def add_friend(friend)
    if (!self.friends.include? friend.id)
        self.push(friends: friend.id)
        self.save
   
        friend.push(friends: self.id)
        friend.save
    else
      false
    end
  end

    def remove_friend(friend)
      self.delete_at(friends: friend.id)
    end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		comment = post.comments.create(comment_params)
		redirect_to user_post_path(post.user, post)
	end

	private
	def comment_params
		params.require(:comment).permit(:body)

	end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.all
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.create(friend_params)
    if @friend.save
      redirect_to friends_path
    else
      render :new
    end
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def friend_params
    params.require(:friend).permit(:firstname, :lastname, :email, :address, :city, :state, :zip, :password)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])

    @comment = Comment.new
  end

  def new
    @user = User.find(params[:user_id])
    if logged_in? && @user == current_user
      @post = Post.new
    else
      redirect_to users_path
    end
    
    

  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
  	if @post.save
  		redirect_to user_posts_path
  	else
  		render :new
  	end

  end

  private
  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
  	user = User.where(email: params[:login][:email]).first
  	if user && user.authenticate(params[:login][:password])
        session[:user_id] = user.id.to_s
      	redirect_to user_path(user)

    else
      	redirect_to login_path
    end
  end
  
  def destroy
  	session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)

      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if(params[:id] == session[:user_id])
      session.delete(:user_id)
    end
    @user.destroy
    redirect_to users_path
  end

  def calendar
    @time = Time.now
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :address, :city, :state, :zip, :password, :password_confirmation, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper

	def calendar
		cal = "<table border='1'><tr>"
		days = %w(sun mon tue wed thu fri sat)
		days.each do |day|
			cal += "<td> #{day} </td>"
		end
		cal += "</tr></table>"
		return cal
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
  	if(session[:user_id])

    @current_user ||= User.find(session[:user_id])
	  end
  end

  def logged_in?
  	session[:user_id] != nil
  
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/create.html.erb
<h1>Friends#create</h1>
<p>Find me in app/views/friends/create.html.erb</p>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<h1><%= form_for @friend </h1>

app/views/friends/index.html.erb
<h1> Friend's page</h1>
<ul>
	<% @friends.each do |f| %>
	<li>
		<%= link_to f.fullname, friend_path(f) %><br>
		<%= f.address %><br>
		<%= f.city %>, <%= f.state %>  <%= f.zip %><br>
		<%= f.email %><br>
		<br>

	</li>
	<% end %>
</ul>

<%= link_to "Add New Friend", new_friend_path %>

app/views/friends/new.html.erb
<h1>Let's Add A New Friend</h1>
<%= form_for @friend do |f| %>

<div>
	<%= f.label :firstname, "FirstName:" %>
	<%= f.text_field :firstname %>
</div>

<div>
	<%= f.label :lastname, "Last Name:" %>
	<%= f.text_field :lastname %>
</div>

<div>
	<%= f.label :email, "Email:" %>
	<%= f.text_field :email %>
</div>

<div>
	<%= f.label :address, "Address:" %>
	<%= f.text_field :address %>
</div>

<div>
	<%= f.label :city, "City:" %>
	<%= f.text_field :city %>
</div>

<div>
	<%= f.label :state, "State:" %>
	<%= f.text_field :state %>
</div>

<div>
	<%= f.label :zip, "Zip:" %>
	<%= f.text_field :zip %>
</div>

<%= f.submit "Submit" %>

<% end %>

app/views/friends/show.html.erb
<h1>Welcome to <%= @friend.fullname %>'s Page</h1>

<ul>
	<li>
		<%= @friend.fullname %><br>
		<%= @friend.address %><br>
		<%= @friend.city %><br>
		<%= @friend.state %><br>
		<%= @friend.zip %><br>
	</li>
</ul>

<%= link_to "Home", friends_path %>

app/views/friends/update.html.erb
<h1>Friends#update</h1>
<p>Find me in app/views/friends/update.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="nav">

	<div class="lognav">
		<% if(current_user) %>
		<% end %>

		<% if logged_in? %>
		  Logged in as: <%= current_user.firstname %> <%= link_to 'Log Out', logout_path, method: :delete %>
		<% else %>
		  <%= link_to 'Log In', login_path %>
		<% end %>
	</div>


	<div class="homenav">
		<%= link_to "Home", users_path %>
	</div>

	<div class="lognav2">
		<%= link_to "Sign Up", signup_path %>
	</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Starletface</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>

	<%= render 'layouts/nav' %>
	<%= yield %>

	</body>
	
</html>

app/views/posts/index.html.erb
<div class="margin">

	<h1>My Awesome Blog Posts</h1>

		<% @posts.each do |post| %>
			<div>
				<%= link_to post.title, user_post_path(@user, post) %>
			</div>
		<% end %>
	<br>
		<% if current_user == @user %>
		<%= link_to "Add New Post", new_user_post_path(@user) %>
		<% end %>

	<br>
	<br>

</div>

app/views/posts/new.html.erb
<div class="margin">
	<h1>Add a new blog post</h1>

		<%= form_for [@user, @post], url: user_posts_path do |p| %>
			
			<div>
				<%= p.label :title, "Title" %>
				<%= p.text_field :title %>
			</div>

			<div>
				<%= p.text_area :body %>
			</div>

			<%= p.submit "Add this blog post" %>

		<% end %>

		<%= link_to "Post", user_posts_path(@user) %>

</div>

app/views/posts/show.html.erb
<div class="margin">

	<header>
		<h1><%= @post.title %></h1> 
		<h5>Post on <%= @post.date_published %></h5>
	</header>

	<article>
		<p><%= @post.body %></p>
	</article>

	<section class="comment">
		<h3>Comments</h3>
			<div>
				<% @post.comments.each do |c| %>
					<div>
						<p><%= c.body %> (added: <%= c.date_added %>)</p>
					</div>
				<% end %>
			</div>
	</section>

	<section>
		<h3>Add a new comment</h3>
		<%= form_for [@post.user, @post, @comment] do |f| %>
			<div>
				<%= f.label :body, "Comment:" %>
				<%= f.text_area :body %>
			</div>

			<%= f.submit "Add a comment" %>
		<% end %>
	</section>

	<h1>test!</h1>
	<%= link_to "Post", user_posts_path %>

</div>

app/views/users/edit.html.erb
<div class="margin"><h1>Edit User</h1>

	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		<% end %>
	</ul>

	<%= form_for @user do |u| %>

		<div>
			<%= u.label :firstname, "First Name:" %>
			<%= u.text_field :firstname %>
		</div>

		<div>
			<%= u.label :lastname, "Last Name:" %>
			<%= u.text_field :lastname %>
		</div>

		<div>
			<%= u.label :email, "Email:" %>
			<%= u.text_field :email %>
		</div>

		<div>
			<%= u.label :address, "Address:" %>
			<%= u.text_field :address %>
		</div>

		<div>
			<%= u.label :city, "City:" %>
			<%= u.text_field :city %>
		</div>

		<div>
			<%= u.label :state, "State:" %>
			<%= u.text_field :state %>
		</div>

		<div>
			<%= u.label :zip, "Zip:" %>
			<%= u.text_field :zip %>
		</div>

		<%= u.submit "Submit Change" %><br><br>

		<%= link_to "Delete this user", :user, method: :delete, data: {confirm: "Are you sure?"} %>
		
	<% end %>

</div>

app/views/users/index.html.erb
<div class="margin">
	<h1>StarFace</h1>
	<p>Where The Stars And The Wannabe Stars Meet To Show Their Pretty, Handsome Faces And Post About Their Useless ***t!</p>


		<div class="index">
			<ul>
				<% @users.each do |u| %>
					<li class="list">
						<%= link_to image_tag u.image.url(:thumb)%>
						<%= link_to u.fullname, user_path(u) %>
					</li>
				<% end %>
			</ul>
		</div>

<br>

app/views/users/new.html.erb
<div class="margin">
	<h1>Sign Up</h1>

		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
			<% end %>

		</ul>


		<%= form_for @user do |u| %>

			<div class="labels">
				<%= u.label :firstname, "First Name:" %>
				<%= u.text_field :firstname %>
			</div>

			<div>
				<%= u.label :lastname, "Last Name:" %>
				<%= u.text_field :lastname %>
			</div>

			<div>
				<%= u.label :email, "Email:" %>
				<%= u.text_field :email %>
			</div>

			<div>
				<%= u.label :address, "Address:" %>
				<%= u.text_field :address %>
			</div>

			<div>
				<%= u.label :city, "City:" %>
				<%= u.text_field :city %>
			</div>

			<div>
				<%= u.label :state, "State:" %>
				<%= u.text_field :state %>
			</div>

			<div>
				<%= u.label :zip, "Zip:" %>
				<%= u.text_field :zip %>
			</div>

			<div>
				<%= u.label :password %>
				<%= u.password_field :password %>
			</div>

		    <div>
		        <%= u.label :password_confirmation %>
		        <%= u.password_field :password_confirmation %>
		    </div>

			<%= u.file_field :image %>
			
			<br>
			<br>

			<%= u.submit "Add New User" %>

		<% end %>


</div>

app/views/users/show.html.erb
<div class="margin">
	<div class="show">
		<h1> Welcome to <%= @user.firstname %>'s page</h1>
		<H2>Here are my info:</H2>

			<%= image_tag(@user.image_url(:full)) %><br>
			<%= @user.firstname %> <%= @user.lastname %><br>
			<%= @user.address %><br>
			<%= @user.city %>, <%= @user.state %>  <%= @user.zip %><br>
			<%= @user.email %><br>

			<br>

		<ul class="user-post-show">
			<% @user.posts.each do |u| %>
				<li>
					<%= link_to u.title, user_post_path(@user, u) %>
				</li>
			<% end %> 
		</ul>			
			
		<% if current_user == @user %>
			<%= link_to "Post", user_posts_path(@user) %>
			<%= link_to "Edit", edit_user_path %>
		<% end %>
		
	</div>
</div>